example:
  projectName: example
  debug: false
  excluded:
    #./libs/*	
    ./libs/Nette/*
    ./temp/*
    ./docs/*
    ./libs/Asdf/Diagnostics/*
    ./log/*
    ./www/*
  watchers:
    phpUnit:
      ext: php
      script: phpunit -c %projectDir%/tests/
      #outputAlways: true
    sniffer:
      ext: php
      script: "phpcs --standard=%watcherDir%/phpcs.xml --tab-width=4 -s %filePath%"
    phpmd:
      ext: php
      script: "phpmd %filePath% text %watcherDir%/phpmd.xml"
    sass:
      ext: sass
      script: sass %filePath% %fileDir%/../%fileBasename%.css -t compressed --trace