example:
  projectName: example
  debug: true
  excluded:
    ./temp/*
  watchers:
    phpUnit:
      pattern: .*\.php
      script: phpunit -c @projectDir/tests/
      outputAlways: true
    sniffer:
      pattern: .*\.php
      script: "phpcs --standard=@projectDir/phpcs.xml --tab-width=4 -s @filePath"
    phpmd:
      pattern: .*\.php
      script: "phpmd @filePath text @projectDir/phpmd.xml"
    phpcpd:
      pattern: .*\.php
      script: "phpcpd @projectDir/client"
    sass:
      pattern: .*\.sass
      script: sass @filePath @fileDir/../@fileBasename.css -t compressed --trace
    less:
      pattern: .*\.less
      script: lessc @filePath @fileDir/../@fileBasename.css --yui-compress